name: Build and Deploy

on:
  push:
    branches:
      - master  # 监听 main 分支的推送事件

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4.0.0

      # 2. 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.23'  # 指定 Go 版本

      # 3. 构建项目
      - name: Build project
        run: |
          go mod tidy
          go build -o message-push

      # 4. 将构建结果打包
      - name: Package artifacts
        run: |
          mkdir -p dist
          tar -czvf dist/message-push.tar.gz message-push app_config.json

      # 5. 部署到服务器（使用最新 scp-action）
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}               # 服务器 IP 地址
          username: ${{ secrets.SSH_SERVERNAME }}         # 服务器用户名
          key: ${{ secrets.SSH_PRIVATE_KEY }}          # 服务器 SSH 私钥
          source: "dist/message-push.tar.gz"
          target: ${{ secrets.DEPLOY_PATH }}           # 服务器部署路径

      # 6. 部署到私有服务器
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # 服务器 SSH 私钥
          SERVER_IP: ${{ secrets.SSH_HOST }}             # 服务器 IP 地址
          SERVER_USER: ${{ secrets.SSH_SERVERNAME }}         # 服务器用户名
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}         # 服务器部署路径
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no dist/message-push.tar.gz $SERVER_USER@$SERVER_IP:$DEPLOY_PATH
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
            cd $DEPLOY_PATH &&
            tar -xzvf message-push.tar.gz &&
            chmod +x message-push &&
            pkill -f message-push || true &&
            nohup ./message-push --config app_config.json &
          "
