name: Build and Deploy

on:
  push:
    branches:
      - master  # 监听 master 分支的推送事件

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4.0.0

      # 2. 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.23'  # 指定 Go 版本

      # 3. 构建项目
      - name: Build project
        run: |
          go mod tidy
          go build -o message-push

      # 4. 将构建结果打包
      - name: Package artifacts
        run: |
          mkdir -p dist
          tar -czvf dist/message-push.tar.gz message-push app_config.json

      # 5. 部署到服务器（使用 scp-action）
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}               # 服务器 IP 地址
          username: ${{ secrets.SSH_USERNAME }}       # 服务器用户名
          key: ${{ secrets.SSH_PRIVATE_KEY }}         # 服务器 SSH 私钥
          source: "dist/message-push.tar.gz"
          target: ${{ secrets.DEPLOY_PATH }}          # 服务器部署路径

      # 6. 在服务器上解压并重启服务（使用 nohup）
      - name: Restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            tar -xzvf message-push.tar.gz
            chmod +x message-push

            # 停止当前运行的 message-push 服务
            pkill -f message-push || true

            # 使用 nohup 后台启动服务
            nohup ./message-push --config app_config.json &